import Foundation
import XCTest
@testable import ArmaziCore

final class BenchmarkParserTests: XCTestCase {

    func testParseBundled() throws {
        let benchmark = try BenchmarkParser.loadBundled()
        XCTAssertEqual(benchmark.name, "CIS macOS Benchmark")
        XCTAssertEqual(benchmark.platform, "macOS")
        XCTAssertFalse(benchmark.checks.isEmpty)
    }

    func testAllChecksHaveRequiredFields() throws {
        let benchmark = try BenchmarkParser.loadBundled()
        for check in benchmark.checks {
            XCTAssertFalse(check.id.isEmpty, "Check ID should not be empty")
            XCTAssertFalse(check.title.isEmpty, "Check title should not be empty for \(check.id)")
            XCTAssertFalse(check.audit.command.isEmpty, "Audit command should not be empty for \(check.id)")
            XCTAssertGreaterThanOrEqual(check.level, 1, "Level should be >= 1 for \(check.id)")
        }
    }

    func testCategoriesCoverAllTypes() throws {
        let benchmark = try BenchmarkParser.loadBundled()
        let categories = Set(benchmark.checks.map(\.category))
        for category in CheckCategory.allCases {
            XCTAssertTrue(categories.contains(category), "Bundled benchmark has no checks for \(category.rawValue)")
        }
    }

    func testCheckIDsAreUnique() throws {
        let benchmark = try BenchmarkParser.loadBundled()
        let ids = benchmark.checks.map(\.id)
        XCTAssertEqual(Set(ids).count, ids.count, "Bundled benchmark contains duplicate check IDs")
    }

    func testChecksMatchingOnPASSCanEmitIt() throws {
        // Most checks echo "PASS: ..." from their audit script. A check that
        // matches on "PASS" but never prints it can only ever fail.
        let benchmark = try BenchmarkParser.loadBundled()
        for check in benchmark.checks {
            guard case .contains(let value) = check.audit.match, value == "PASS" else { continue }
            XCTAssertTrue(check.audit.command.contains("PASS"), "Check \(check.id) matches on PASS but never emits it")
        }
    }

    func testEmbeddedBenchmarkMatchesSourceYAML() throws {
        // EmbeddedBenchmarks.swift is generated by Scripts/embed_benchmarks.py.
        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // ArmaziTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // package root
        let yamlURL = packageRoot
            .appendingPathComponent("Sources/ArmaziCore/Benchmarks/cis-macos-benchmark.yaml")

        guard let source = try? String(contentsOf: yamlURL, encoding: .utf8) else {
            throw XCTSkip("Benchmark source YAML is not available in this environment")
        }

        XCTAssertEqual(
            source,
            EmbeddedBenchmarks.cisMacOS,
            "Embedded benchmark is out of date — run: python3 Scripts/embed_benchmarks.py"
        )
    }

    func testParseYAMLFromString() throws {
        let yaml = """
        name: "Test Benchmark"
        version: "0.1"
        platform: "macOS"
        description: "Test"
        checks:
          - id: "T.1"
            title: "Echo test"
            description: "Should pass"
            category: "access_security"
            level: 1
            scored: true
            audit:
              command: "echo hello"
              match:
                type: "contains"
                value: "hello"
            remediation: "N/A"
            frameworks: ["cis"]
        """
        let benchmark = try BenchmarkParser.parse(yaml: yaml)
        XCTAssertEqual(benchmark.name, "Test Benchmark")
        XCTAssertEqual(benchmark.checks.count, 1)
        XCTAssertEqual(benchmark.checks[0].id, "T.1")
    }
}
